// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC449bCqc1rKne2BzZwsUj3HVku6fwdIxg',
    appId: '1:51337671710:web:54d0a3c2187b35f56fea0f',
    messagingSenderId: '51337671710',
    projectId: 'plant-house-1b291',
    authDomain: 'plant-house-1b291.firebaseapp.com',
    storageBucket: 'plant-house-1b291.appspot.com',
    measurementId: 'G-YY9LFT4VHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxTQRimj5GP0b7ZCPbWIZ5vLY6GWEzWzA',
    appId: '1:51337671710:android:b4095e703234f7f56fea0f',
    messagingSenderId: '51337671710',
    projectId: 'plant-house-1b291',
    storageBucket: 'plant-house-1b291.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCELPDYODbj_aswQORmAjQRBgwLFzgvCVM',
    appId: '1:51337671710:ios:8b2847b86d3776306fea0f',
    messagingSenderId: '51337671710',
    projectId: 'plant-house-1b291',
    storageBucket: 'plant-house-1b291.appspot.com',
    androidClientId: '51337671710-pap8d1nur8bhdmmc5eojkot6mfs798e9.apps.googleusercontent.com',
    iosClientId: '51337671710-amca9l3hspto6b1l71lu4vb8iqvfm1a1.apps.googleusercontent.com',
    iosBundleId: 'com.planthouse.plantHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCELPDYODbj_aswQORmAjQRBgwLFzgvCVM',
    appId: '1:51337671710:ios:11de39fe831827eb6fea0f',
    messagingSenderId: '51337671710',
    projectId: 'plant-house-1b291',
    storageBucket: 'plant-house-1b291.appspot.com',
    androidClientId: '51337671710-pap8d1nur8bhdmmc5eojkot6mfs798e9.apps.googleusercontent.com',
    iosClientId: '51337671710-7dd3v6n3o0jt23erj4m8037r2flrj9vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantHouse',
  );
}
